### ISSUE TITLE
How to add color

### ISSUE THREAD

**Issue by DataStrategist** [56north/hexamapmaker#1]
Hi! I'd like to add color to a hexmap, could you expand your examples to show that? Thanks!

**Comment by mikkelkrogsholm** [comment]
# Add color by using the fill argument in ggplot.

# Remember to remove it from the geom_polygon then

ggplot(zz, aes(x, y, group = id, fill = id)) +
  geom_polygon(colour="black") +
  coord_fixed(ratio = 1)
